spring:
  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true

mybatis-plus:
  type-aliases-package: cc.*.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false
    db-config:
      select-strategy: not_empty


logging:
  level:
    root: info
    cc.tong: debug
server:
  port: 10001
  servlet:
    context-path: /api/


shiro:
  # session 超时时间，单位为秒
  session_timeout: 3600
  cookie_timeout: 86400
  anon_url: /test/**,/febs/**,/img/**,/layui/**,/json/**,/images/captcha,/regist,/actuator/**
  # 登出 url
  login_url: /login
  logout_url: /logout
  # 首页 url
  success_url: /index
  # 未授权跳转 url
  unauthorized_url: unauthorized
