spring:
  redis:
    # Redis数据库索引（默认为 0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 5000

mybatis-plus:
  type-aliases-package: cc.*.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false
    db-config:
      select-strategy: not_empty


logging:
  level:
    root: info
    cc.tong: debug
server:
  port: 10001
  servlet:
    context-path: /api/

shiro:
  # session 超时时间，单位为秒
  session_timeout: 3600
  cookie_timeout: 86400
  anon_url: /test/**,/febs/**,/img/**,/layui/**,/json/**,/images/captcha,/regist,/actuator/**
  # 登出 url
  login_url: /login
  logout_url: /logout
  # 首页 url
  success_url: /index
  # 未授权跳转 url
  unauthorized_url: unauthorized
